
export const movieCards = [
    {
      id: 1,
      title: "Stranger Things",
      genre: ["Drama", "Fantasy", "Thriller"],
      description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
      image: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
      rating: 8.7,
      year: 2016,
      ageLimit: "16+",
    },
    {
      id: 2,
      title: "Money Heist",
      genre: ["Action", "Crime", "Drama"],
      description: "A criminal mastermind who goes by 'The Professor' plans the biggest heist in recorded history — to print billions of euros in the Royal Mint of Spain.",
      image: "https://m.media-amazon.com/images/M/MV5BZjkxZWJiNTUtYjQwYS00MTBlLTgwODQtM2FkNWMyMjMwOGZiXkEyXkFqcGc@.jpg",
      rating: 8.2,
      year: 2017,
      ageLimit: "18+",
    },
    {
      id: 3,
      title: "Dark",
      genre: ["Sci-Fi", "Mystery", "Thriller"],
      description: "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the dark past of four families.",
      image: "https://image.tmdb.org/t/p/w500/8u0QBGUbZcBW59VEAdmeFl9g98N.jpg",
      rating: 8.8,
      year: 2017,
      ageLimit: "16+",
    },
    {
      id: 4,
      title: "The Witcher",
      genre: ["Fantasy", "Action", "Adventure"],
      description: "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
      image: "https://image.tmdb.org/t/p/w500/zrPpUlehQaBf8YX2NrVrKK8IEpf.jpg",
      rating: 8.1,
      year: 2019,
      ageLimit: "18+",
    },
    {
      id: 5,
      title: "The Queen’s Gambit",
      genre: ["Drama"],
      description: "Orphaned at the tender age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1960s USA.",
      image: "https://image.tmdb.org/t/p/w500/zU0htwkhNvBQdVSIKB9s6hgVeFK.jpg",
      rating: 8.6,
      year: 2020,
      ageLimit: "16+",
    },
    {
      id: 6,
      title: "Breaking Bad",
      genre: ["Crime", "Drama", "Thriller"],
      description: "A chemistry teacher diagnosed with cancer turns to making and selling methamphetamine to secure his family’s future.",
      image: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
      rating: 9.5,
      year: 2008,
      ageLimit: "18+",
    },
    {
      id: 7,
      title: "Squid Game",
      genre: ["Drama", "Thriller"],
      description: "Hundreds of cash-strapped contestants accept an invitation to compete in children's games for a tempting prize — but the stakes are deadly.",
      image: "https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
      rating: 8.0,
      year: 2021,
      ageLimit: "18+",
    },
    {
      id: 8,
      title: "Wednesday",
      genre: ["Comedy", "Fantasy", "Mystery"],
      description: "Follows Wednesday Addams' years as a student at Nevermore Academy, where she attempts to master her psychic ability and solve mysteries.",
      image: "https://image.tmdb.org/t/p/w500/jeGtaMwGxPmQN5xM4ClnwPQcNQz.jpg",
      rating: 8.3,
      year: 2022,
      ageLimit: "13+",
    }
  ];
